service: nihao # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1

functions:
  replyMessage:
    handler: handlers/messageHandlers.replyMessage
    events:
      - http:
          path: reply
          method: post
          integration: lambda
          authorizer:
            arn: arn:aws:cognito-idp:us-east-1:646898565065:userpool/us-east-1_bpYWRgIrp

