service: nihao

provider:
  name: aws
  runtime: nodejs6.10
  stage: v1
  region: us-east-1

functions:

  optionsHandle:
    handler: handlers/httpOptionsHandlers.handle
    events:
      - http:
          path: /{any+}
          method: options
          cors: true

  replyMessage:
    handler: handlers/messageHandlers.replyMessage
    events:
      - http:
          path: reply
          method: post
          authorizer:
            arn: arn:aws:cognito-idp:us-east-1:646898565065:userpool/us-east-1_bpYWRgIrp

  lexFulfilled:
      handler: handlers/messageHandlers.lexFulfilledHookHandler

  checkMessageQueue:
    handler: handlers/messageHandlers.checkMessageQueue
    events:
      - schedule: rate(1 minute)


